export const data = [
  // Chicken Food
  {
    id: 1,
    category: "Chicken Food",
    name: "bbq-chicken_1",
    img: "/assets/chicken-food/bbq-chicken_1.jpg",
    description: "Juicy grilled chicken coated in smoky BBQ sauce.",
    price: 12.99,
  },
  {
    id: 2,
    category: "Chicken Food",
    name: "florida-chicken",
    img: "/assets/chicken-food/florida-chicken.jpg",
    description: "Tender chicken with a tropical citrus marinade.",
    price: 13.49,
  },
  {
    id: 3,
    category: "Chicken Food",
    name: "mushroom-chicken_2",
    img: "/assets/chicken-food/mushroom-chicken_2.jpg",
    description: "Chicken breast topped with creamy mushroom sauce.",
    price: 14.25,
  },
  {
    id: 4,
    category: "Chicken Food",
    name: "mustard-chicken_1",
    img: "/assets/chicken-food/mustard-chicken_1.jpg",
    description: "Grilled chicken infused with tangy mustard flavor.",
    price: 12.75,
  },

  // Cold Appetizers
  {
    id: 5,
    category: "Cold Appetizers",
    name: "hummus-1_1",
    img: "/assets/cold-appetizers/hummus-1_1.jpg",
    description: "Classic creamy hummus served with olive oil.",
    price: 6.5,
  },
  {
    id: 6,
    category: "Cold Appetizers",
    name: "hummus-pesto_2",
    img: "/assets/cold-appetizers/hummus-pesto_2.jpg",
    description: "Traditional hummus blended with fresh pesto.",
    price: 7.25,
  },
  {
    id: 7,
    category: "Cold Appetizers",
    name: "mohamara_2",
    img: "/assets/cold-appetizers/mohamara_2.jpg",
    description: "Spicy walnut and red pepper dip, rich in flavor.",
    price: 7.75,
  },
  {
    id: 8,
    category: "Cold Appetizers",
    name: "mtabal-batenjan_4",
    img: "/assets/cold-appetizers/mtabal-batenjan_4.jpg",
    description: "Smoky eggplant dip mixed with tahini and lemon.",
    price: 6.99,
  },

  // Hot Appetizers
  {
    id: 9,
    category: "Hot Appetizers",
    name: "hummus-with-beef_1",
    img: "/assets/hot-appetizers/hummus-with-beef_1.jpg",
    description: "Creamy hummus topped with sautéed beef.",
    price: 8.5,
  },
  {
    id: 10,
    category: "Hot Appetizers",
    name: "hummus-with-beef-shawarma",
    img: "/assets/hot-appetizers/hummus-with-beef-shawarma.jpg",
    description: "Hummus served with flavorful beef shawarma.",
    price: 9.25,
  },
  {
    id: 11,
    category: "Hot Appetizers",
    name: "hummus-with-chicken-shawarma",
    img: "/assets/hot-appetizers/hummus-with-chicken-shawarma.jpg",
    description: "Hummus topped with tender chicken shawarma.",
    price: 8.99,
  },
  {
    id: 12,
    category: "Hot Appetizers",
    name: "makanek_2",
    img: "/assets/hot-appetizers/makanek_2.jpg",
    description: "Lebanese spiced sausages sautéed to perfection.",
    price: 9.5,
  },

  // Mashawi
  {
    id: 13,
    category: "Mashawi",
    name: "kafta",
    img: "/assets/mashawi/kafta.jpg",
    description: "Grilled minced meat skewers seasoned with herbs.",
    price: 11.99,
  },
  {
    id: 14,
    category: "Mashawi",
    name: "lahme",
    img: "/assets/mashawi/lahme.jpg",
    description: "Succulent grilled lamb cubes served hot off the grill.",
    price: 13.99,
  },
  {
    id: 15,
    category: "Mashawi",
    name: "mix-platters",
    img: "/assets/mashawi/mix-platters.jpg",
    description: "A generous platter of assorted grilled meats.",
    price: 18.5,
  },
  {
    id: 16,
    category: "Mashawi",
    name: "tawouk_1",
    img: "/assets/mashawi/tawouk_1.jpg",
    description: "Marinated chicken skewers grilled to golden perfection.",
    price: 12.25,
  },

  // Salads
  {
    id: 17,
    category: "Salads",
    name: "fattouch",
    img: "/assets/salads/fattouch.jpg",
    description: "Fresh mixed salad with crispy bread and tangy dressing.",
    price: 6.75,
  },
  {
    id: 18,
    category: "Salads",
    name: "rocca_2",
    img: "/assets/salads/rocca_2.jpg",
    description: "Simple arugula salad with lemon and olive oil.",
    price: 6.25,
  },
  {
    id: 19,
    category: "Salads",
    name: "rocca-with-betroot",
    img: "/assets/salads/rocca-with-betroot.jpg",
    description: "Arugula salad topped with sweet roasted beetroot.",
    price: 7.25,
  },
  {
    id: 20,
    category: "Salads",
    name: "tabbouleh_4",
    img: "/assets/salads/tabbouleh_4.jpg",
    description: "Traditional parsley salad with bulgur, tomato, and lemon.",
    price: 6.99,
  },
];
